### ISSUE TITLE
[meta] Migration to AMO

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#486]
This is a meta bug designed for tracking work migrating into central or web extensions.
I will update the checkbox here as it will likely require bugzilla work too.
This won't be all of the migration of the test pilot to central, for example the browser action might be migrated much later, this is purely to prevent a 57 deprecation issue.

- [x] SDK removal of web extensions work
    - https://github.com/mozilla/testpilot-containers/pull/485
    - https://github.com/mozilla/testpilot-containers/pull/487
    - Removal of conversion methods (icon and color)
- [x] Transition of new tab hover
- [x] Platform meta https://bugzilla.mozilla.org/show_bug.cgi?id=1354601
  - [x] Move containers highlight to be an underline [Bug 1325902](https://bugzilla.mozilla.org/show_bug.cgi?id=1325902)
  - [x] Containers events [Bug 1344519](https://bugzilla.mozilla.org/show_bug.cgi?id=1344519)
  - [x] Enable containers [Bug 1354602](https://bugzilla.mozilla.org/show_bug.cgi?id=1354602)
  - [x] Icon changes: https://bugzilla.mozilla.org/show_bug.cgi?id=1387003
- [x] Transition of new icons to central
- [x] Preference flipping via web extensions?

**Comment by jonathanKingston** [comment]
Remove icon code: #603

**Comment by jonathanKingston** [comment]
Final work for the non central work is completed here: https://github.com/mozilla/testpilot-containers/pull/605

**Comment by jonathanKingston** [comment]
#605 has become also the integration with AMO work.

The work there allows developers to use:
```
web-ext run -p profile-with-containers-enabled -f nightly-dir
```

This allows `about:debugging` and all other web extension goodness.

Not supported are:
- Telemetry
- Tab utils
  - Moving
  - Sorting
- Assignment state isn't correct

**Comment by jonathanKingston** [comment]
We should probably consider the implications of dropping all index.js code.

Currently we don't have:
- Tab highlight change
- Container modification on startup (this actually could be moved however existing users data would have to be taken out of index storage)
- Add button would have a manage button which will link to about:preferences (which has a subset of icons)

I added back in the index.js which no longer has any inbound requests to it. The only thing it does is opens tabs in web extensions.

**Comment by jonathanKingston** [comment]
So @groovecoder this code will now work (possibly with bugs) enabling the tab higlight, manipulating prefs and setting up default containers via sdk.
I think we can move those bits to bootstrap would that be worth doing?

My hunch is it won't be worth doing as all of these 3 things will be changed in central before 57. We might not even care about the storage they have for prefs if we push the addon to everyone also.

In which case this just needs testing and bugs removed, then we can fix the last code changes in central (we will have to ride the trains for these which will take a while though).

**Comment by groovecoder** [comment]
I think we can close this? We've got all the code working on AMO. We just need to close out the last tasks on https://github.com/mozilla/testpilot-containers/issues/665 to migrate all Test Pilot users to AMO and "graduate" the add-on from Test Pilot.
