### ISSUE TITLE
[Softvision QA] Testing report for shield-study-containers build v2.3.0

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot-containers#617]
Hi everyone,

We managed to run almost all the tests from the provided Test Plan and we also did some exploratory testing afterwards. Here are the testing results for the provided build:

**New Issues:**
1. #607 - Checkbox for "Remember my decision for this site" is not in line with the text
2. #608 - The green "New" badge changes its color to red in new opened windows
3. #609 - There is no tooltip that displays the full container name
4. #610 - "Always open in this container" option is checked in other containers even if the website is not assigned to them (marked as dupe to #606)
5. #611 - "Always open in this container" option is checked in other containers even if the website is not assigned to them
6. #612 - "Always open in Default" is grayed out and unusable 
7. #613 - "Sort Tabs" option affects more than just the current window if there are at least 2 opened windows
8. #614 - Disabling Containers from about:addons wrongly removes the add-on 
9. #615 - There is no tooltip that displays the full website URL from a container 
10. #616 - [Mac OS] The Containers "New Tab" menu wrongly opens behind other Firefox toolbar doorhangers / menus 

**Other observed behaviors:**
1. After successful install, a new tab is opened displaying just a message of thanks for participating in the shield study (http://imgur.com/a/sbSiq). 
-  Is this ok? Will the end users get it too?
2. If both the Shield study xpi and Test Pilot Containers add-ons are installed, when removing the Test Pilot version, the containers opened with the Shield study one break quite bad.
- Let us know if you want us to log something for this.
3. We could not test the update functionality.
- We have tested just the update from a normal build to the latest version. But if you install the shield study xpi afterwards, you end up with 2 Containers add-ons installed. If this shield study build should replace the current Test Pilot version, then we might have an issue. Let us know your thoughts on this.

**Comment by kjozwiak** [comment]
@SoftVision-PaulOiegas, thank you so much for all the effort your team put into this! It's definitely appreciated 👍 

I went through all of the bugs and triaged them into three categories inside the Shield milestone:

* High - Should be fixed before we release the Shield Study
* Medium - Would be nice to fix it, but not the end of the world if we don't have the resources/time
* Low - Only fix if it's really trivial and won't waste resources that could be used on the higher bugs

> #607 - Checkbox for "Remember my decision for this site" is not in line with the text

Marked this as low but we should fix this as it affects the UI of an integral part of containers. Because we're going to have to fix #606, #611 and #614, this trivial fix can easily ride along with those fixes into the new build.

> #608 - The green "New" badge changes its color to red in new opened windows

Marked this as low as it's not a new regression and currently exists in the current `2.3.0` release of the experiment.

> #609 - There is no tooltip that displays the full container name

We can probably close this off and keep #112 to follow the tooltip work. Either way, it's definitely a low.

> #610 - "Always open in this container" option is checked in other containers even if the website is not assigned to them (marked as dupe to #606)

Dupe of #606 which is marked as high and should be fixed before we release the shield study. This breaks functionality in an obvious way.

> #611 - "Always open in this container" option is checked in other containers even if the website is not assigned to them

Marked this as high and should be fixed before we release the shield study as it breaks  functionality in an obvious way.

> #612 - "Always open in Default" is grayed out and unusable

Closed as this is the intended behaviour. We've had similar requests via #503.

> #613 - "Sort Tabs" option affects more than just the current window if there are at least 2 opened windows

The sort feature has been behaving this way since the beginning of the test pilot. Tested it against older versions and it's the same behaviour. Enhancement rather than a bug.

> #614 - Disabling Containers from about:addons wrongly removes the add-on

Marked this as high as it's a regression in this new version of the XPI and doesn't occur in the currently released 2.3.0 version. I'm not sure if the "disable" feature is actually being use by users or if it will have negative affects on the shield study once it's removed. Should probably fix this before releasing.

> #615 - There is no tooltip that displays the full website URL from a container

We can probably close this off and keep #112 to follow the tooltip work. Either way, it's definitely a low.

> #616 - [Mac OS] The Containers "New Tab" menu wrongly opens behind other Firefox toolbar doorhangers / menus

Marked this as a low as these types of issues (example: #95) have been around since the beginning of the test pilot.

**Comment by SoftVision-PaulOiegas** [comment]
@kjozwiak You welcome, we are glad that we could help and sorry for the delay. The email somehow got between all Containers repository messages and I missed it.

Have you guys looked also over the other possible issues mentioned under the bugs ? Haven't seen any details about those. Let us know if you consider any of them issues and want us to file them.

**Comment by jonathanKingston** [comment]
@SoftVision-PaulOiegas thanks for testing this!

> After successful install, a new tab is opened displaying just a message of thanks for participating in the shield study (http://imgur.com/a/sbSiq).

This is fixed with the variation code that I just merged. It should be picking a different route to introduction.

> If both the Shield study xpi and Test Pilot Containers add-ons are installed, when removing the Test Pilot version, the containers opened with the Shield study one break quite bad.

@groovecoder @johngruen are we sure we can prevent this from happening?

> We could not test the update functionality.

You would have to build shield itself as it has a different package name which is what causes this. The steps for this are in the README. However I think @kjozwiak has extensively tested this for Shield and also the test pilot versions.

Thanks
Jonathan

**Comment by jonathanKingston** [comment]
- [ ] #607 - Checkbox for "Remember my decision for this site" is not in line with the text
- [ ] #608 - The green "New" badge changes its color to red in new opened windows
- [ ] #609 - There is no tooltip that displays the full container name
- [ ] #610 - "Always open in this container" option is checked in other containers even if the website is not assigned to them (marked as dupe to #606)
- [ ] #611 - "Always open in this container" option is checked in other containers even if the website is not assigned to them
- [ ] #612 - "Always open in Default" is grayed out and unusable 
- [ ] #613 - "Sort Tabs" option affects more than just the current window if there are at least 2 opened windows
- [ ] #614 - Disabling Containers from about:addons wrongly removes the add-on 
- [ ] #615 - There is no tooltip that displays the full website URL from a container 
- [ ]  #616 - [Mac OS] The Containers "New Tab" menu wrongly opens behind other Firefox toolbar

**Comment by jonathanKingston** [comment]
All issues are addressed in PRs or merged.

Left are the comments but I think they are all fine.

Closing this off @SoftVision-PaulOiegas, @kjozwiak and @groovecoder feel free to reopen if that isn't the case.

**Comment by jonathanKingston** [comment]
Reopening on the account of the new issues.

**Comment by jonathanKingston** [comment]
- [ ] #624 The browser is closed, if there are only same container tabs and you choose to hide them
- [ ] #625 A container tab is wrongly displayed after restoring a session closed by hiding a container
- [ ] #626 If you refresh the page after assigning it to a container, "Containers confirm navigation" page is wrongly opened in a new tab
- [ ] #630 "Always Open in This Container" notification is displayed differently for some websites
